:sparkles: feat: book devolution endpoint
Tassio2002/library-typescript-api pull request #7
Opened 2023-03-02 21:09 UTC by Tassio2002

Endpoint de devolução de livros e rota para acessar o método.

2023-03-03 13:21 UTC, Givs requested changes

2023-03-03 13:21 UTC, Givs commented on src/controllers/BookController.ts
> +      const booksReserved = user.books_reserved;
use destructuring pra já pegar o books_reserved de user

2023-03-03 13:21 UTC, Givs commented on src/routes/routes.ts
> +router.post("/book/book_devolution/:user_id/:book_id", bookController.bookDevolution)
só confirmar que esse POST não tem envio de json que ai precisaria de middleware, está sendo passado via params

2023-03-03 13:21 UTC, Givs commented on src/controllers/BookController.ts
> +      let isBookReserved: boolean = false;
creio q toda essa lógica das linhas 131 - 142 pode ser melhorada.
vc só precisa verificar se o bookId está em booksReserved, pode usar o método includes(), ai se não tives vc retorna ali o 400 e message

2023-03-04 00:32 UTC, Tassio2002 commented on src/controllers/BookController.ts
> +      const booksReserved = user.books_reserved;
[Resolvido](https://github.com/Tassio2002/library-typescript-api/pull/7/commits/c85152338b960747c53ad96373540b129dba84a2)

2023-03-04 00:33 UTC, Tassio2002 commented on src/routes/routes.ts
> +router.post("/book/book_devolution/:user_id/:book_id", bookController.bookDevolution)
Voce está falando do body da requisição se sim, realmente não tem, tudo é passado como parâmetro na URL.

2023-03-04 00:45 UTC, Tassio2002 commented on src/controllers/BookController.ts
> +      let isBookReserved: boolean = false;
[Resolvido](https://github.com/Tassio2002/library-typescript-api/pull/7/commits/9cf3b9edd75a2b440774d107fdf38770e449cce2)

2023-03-04 02:05 UTC, Givs requested changes

2023-03-04 02:05 UTC, Givs commented on src/controllers/BookController.ts
> +      console.log(isBookReserved)
remover console.log()

2023-03-04 02:05 UTC, Givs commented on src/controllers/BookController.ts
> +      if (isBookReserved === false) {
ao invés de comparar com false vc pode só colocar a negação de isBookReserved dentro desse if. 

```
if (!isBookReserved){
   ....
}
```

2023-03-04 02:05 UTC, Givs commented on src/controllers/BookController.ts
> +      userRepository.save(user);
creio que vc pode usar o Promise.all() pra executar essas 2 operações, pode melhorar a performance
ps: não sei direito se funciona, testa ai

ficaria 
`    await Promise.all([userRepository.save(user), BookRepository.save(book)]);
`

2023-03-04 02:05 UTC, Givs commented on src/controllers/BookController.ts
> +      const bookId = Number(book_id);
linhas 115 e 116 não fazem sentido estarem dentro do bloco try catch

2023-03-04 10:01 UTC, Tassio2002 commented on src/controllers/BookController.ts
> +      console.log(isBookReserved)
Resolvido

2023-03-04 10:52 UTC, Tassio2002 commented on src/controllers/BookController.ts
> +      if (isBookReserved === false) {
Resolvido

2023-03-04 10:52 UTC, Tassio2002 commented on src/controllers/BookController.ts
> +      userRepository.save(user);
Resolvido

2023-03-04 10:52 UTC, Tassio2002 commented on src/controllers/BookController.ts
> +      const bookId = Number(book_id);
[Resolvido](https://github.com/Tassio2002/library-typescript-api/pull/7/commits/eed27e8a56f1b59efcc498067bc645822d138318)

2023-03-04 15:58 UTC, merged